# Book settings
# @see https://jupyterbook.org/customize/config.html#configuration-defaults
title: 音箱 -OTOBAKO-
author: OTOBAKO
copyright: 2020 MKT-SYSTEM Co., Ltd.
logo: img/logo.png

html:
  favicon: img/favicon.png
  extra_navbar: ''
  extra_footer: ''

latex:
  latex_documents:
    targetname: book.tex
